adobe/aio-cli

.travis.yml, README.md, appveyor.yml
=> Added Travis CI and AppVeyor integrations

package-lock.json, package.json
=> Bump to v1.2.1

package.json, src/index.js
=> aim for 100% coverage of branches

src/index.js, test/index.test.js
=> semi cleanup

package.json
*******   *******
******     ******
*****       *****
****    *    ****
***    ***    ***
**    *****    **
*         **    *
=> added logo mark

package-lock.json, package.json
=> Greenkeeper/eslint plugin node 9.0.1

README.md, RELEASING.md, package-lock.json, package.json
Added instructions for incrementing versions after an npm publish
#39
=> Pre release

package-lock.json, package.json
=> Update @adobe/aio-cli-plugin-console to the version 2.0.1

package-lock.json, package.json
=> Update package-lock.json for new @oclif/autocomplete version

README.md
- remove link to aio cli health, it is right there
- add link to getting started
- remove development section
=> Update readme toc

package-lock.json, package.json
=> Greenkeeper/eslint plugin jest 23.1.0

README.md
Remove npm install wskdebug step because it is now a dependency of the template project.
=> remove wskdebug install

README.md
Trivial updates in readme to reflect latest CLI features.
=> Update readme for M1 release changes

package.json
Noticed while working on #107 that there's a reference to a TypeScript definition file that doesn't exist. Based on the commit history I'm guessing this just made it over from a copy/paste of a prior project/boilerplate.
=> Remove reference to missing d.ts lib file in package.json

README.md
Added to documentation how to invoke actions when running app locally.
=> Describe how to invoke actions when running app locally

package-lock.json, package.json
Update a dependency explicitly
npm test
=> chore(package): update @adobe/aio-cli-plugin-auth to ^1.1.0

test/commands/discover.test.js
this changes to only test the output order and not date objects directly
Closes #107 
We had issues with Dates created around midnite on December 31st
added tests, and the original tests are passing
=> consolidate sorting tests

src/commands/update.js
closes #137
manual test
npm test
=> fix: @adobe/aio-cli is listed in the plugins to update

src/commands/update.js, src/helpers.js, test/commands/update.test.js
=> skip version check for plugins that are not on npm

package-lock.json, package.json
Update @adobe/aio-cli-plugin-app, @adobe/aio-cli-plugin-auth, @adobe/aio-cli-plugin-certificate plugins
npm test
=> chore(package): update @adobe/aio-cli-plugin-app, @adobe/aio-cli-plugin-auth, @adobe/aio-cli-plugin-certificate plugins

package-lock.json, package.json
=> Greenkeeper/@adobe/aio cli plugin app 2.0.5

src/commands/discover.js, test/commands/discover.test.js
=> using registry.npmjs.org for search in discover

package.json
=> fix: point main to an existing file

README.md
Links to the Project Firefly documentation page in order to centralize information.
Will help users with issues like #247 (CloudManager plugin use-case).
=> Added technical requirements section

.github/workflows/daily-install-cli.yml
Fixes #249 
Can't test this manually. Need to merge and see how it goes.
=> feat: add daily test install of aio-cli as a Github Action

src/commands/update.js
Added a warning msg for fixing old dependencies remaining in the local npm cache
As a short term solution added a warning msg for fixing old dependencies remaining in the local npm cache
Fixes #269 
See above
1. cloned aio-cli repo
2. ran `node ./bin/run update`
=> Updated update.js for fixing old dependencies remaining in the local npm cache

.github/workflows/daily-install-cli.yml, .github/workflows/on-push-publish-to-npm.yml, .github/workflows/version-bump-publish.yml
=> Only run publish/ci actions on source repo, and not forks

package-lock.json, package.json
=> bump min node version to 12

src/commands/update.js, test/commands/update.test.js
Fixes #193 
`aio update` of core plugins are problematic because sometimes dependencies are not updated properly because some other plugin might need a versioned dependency. The only way to resolve this dependency issue is by reinstalling the cli for core plugins.
`aio update` with user installed core plugins, core plugins that need updates (older cli), general user installed plugins
npm test
=> fix: `aio update` should only update non-core plugins

e2e/e2e.js, package-lock.json
fixes #281 
npm test
npm run e2e
- [X ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
=> fix: npm run e2e is not cross-platform

package-lock.json, package.json
5.6.x contains output changes that break the tests.
npm i && npm test
=> fix: pin cli-ux to 5.5.1

.github/workflows/npm-audit.yml
=> Fix for bootstrapping app with no extensions

README.md
=> fix: add proxy support section in the README

.github/workflows/prerelease-main.yml, .github/workflows/prerelease.yml
This affects the help output.
Running the pre-release action will test it out.
=> fix: for pre-release, the oclif.bin in package.json was not set to aio-next

package-lock.json, package.json
When the CLI is published, bump a minor version.
=> chore(package): update app plugin to v10

.github/workflows/npm-audit.yml
=> fix: ACNA-1825 - daily - npm audit checks are failing with aio-cli@9.x

.github/workflows/node.js.yml
Fixes #388
The checks will run the test
=> fix: ACNA-2081 - remove installing latest npm

package-lock.json, package.json
update to https://github.com/adobe/aio-cli-plugin-events/releases/tag/3.3.0
=> Update @adobe/aio-cli-plugin-events version

README.md
The README.md file has the table of contents (TOC) included twice, this deduplicates the TOC.
=> docs: Deduplicate TOC

package.json
=> Remove archaic package.json ln scripts. This closes #618

package.json
=> Add app-dev command ^1

package-lock.json, package.json
Release prep for 10.3 
- update aio-cli-plugin-app to 13.0
- update aio-cli-plugin-app-dev to 2.0
=> Update app and app-dev plugin major versions

package-lock.json
Fixes #670
Should release a cli patch version with this.
- npm test
=> fix: ACNA-3236 - update package-lock.json for @adobe/aio-lib-ims@7.0.2
